export const FETCH_GOOGLE_BOOK_HAS_ERRORED = 'FETCH_GOOGLE_BOOK_HAS_ERRORED';
export const FETCH_GOOGLE_BOOK_IS_LOADING = 'FETCH_GOOGLE_BOOK_IS_LOADING';
export const FETCH_GOOGLE_BOOK_SUCCESS = 'FETCH_GOOGLE_BOOK_SUCCESS';
