export const FETCH_AMAZON_BOOK_HAS_ERRORED = 'FETCH_AMAZON_BOOK_HAS_ERRORED';
export const FETCH_AMAZON_BOOK_IS_LOADING = 'FETCH_AMAZON_BOOK_IS_LOADING';
export const FETCH_AMAZON_BOOK_SUCCESS = 'FETCH_AMAZON_BOOK_SUCCESS';
export const FETCH_SINGLE_AMAZON_BOOK_SUCCESS =
  'FETCH_SINGLE_AMAZON_BOOK_SUCCESS';
export const CLEAR_AMAZON_BOOKS_SUCCESS = 'CLEAR_AMAZON_BOOKS_SUCCESS';
