export const FETCH_GOODREADS_BOOK_HAS_ERRORED =
  'FETCH_GOODREADS_BOOK_HAS_ERRORED';
export const FETCH_GOODREADS_BOOK_IS_LOADING =
  'FETCH_GOODREADS_BOOK_IS_LOADING';
export const FETCH_GOODREADS_BOOKS_SUCCESS = 'FETCH_GOODREADS_BOOKS_SUCCESS';
export const FETCH_GOODREADS_BOOK_SUCCESS = 'FETCH_GOODREADS_BOOK_SUCCESS';
export const CLEAR_GOODREADS_BOOKS_SUCCESS = 'CLEAR_GOODREADS_BOOKS_SUCCESS';
