export const FETCH_BOOKSHELF_HAS_ERRORED = 'FETCH_BOOKSHELF_HAS_ERRORED';
export const FETCH_BOOKSHELF_IS_LOADING = 'FETCH_BOOKSHELF_IS_LOADING';
export const FETCH_BOOKSHELF_SUCCESS = 'FETCH_BOOKSHELF_SUCCESS';
export const FILTER_BOOKSHELF_SUCCESS = 'FILTER_BOOKSHELF_SUCCESS';
export const SAVE_COMBINED_BOOKS_SUCCESS = 'SAVE_COMBINED_BOOKS_SUCCESS';
export const ADD_BOOK_TO_BOOKSHELF_SUCCESS = 'ADD_BOOK_TO_BOOKSHELF_SUCCESS';
export const ADD_BOOK_TO_BOOKSHELF_FAILURE = 'ADD_BOOK_TO_BOOKSHELF_FAILURE';
export const UPDATE_BOOK_ON_BOOKSHELF_SUCCESS =
  'UPDATE_BOOK_ON_BOOKSHELF_SUCCESS';
export const UPDATE_BOOK_ON_BOOKSHELF_FAILURE =
  'UPDATE_BOOK_ON_BOOKSHELF_FAILURE';
export const SAVE_MODIFIED_BOOKS_SUCCESS = 'SAVE_MODIFIED_BOOKS_SUCCESS';
export const UPDATE_MODIFIED_BOOK_SUCCESS = 'UPDATE_MODIFIED_BOOK_SUCCESS';
export const INSERT_MODIFIED_BOOK_SUCCESS = 'INSERT_MODIFIED_BOOK_SUCCESS';
export const DELETE_BOOK_ON_BOOKSHELF_FAILURE =
  'DELETE_BOOK_ON_BOOKSHELF_FAILURE';
export const DELETE_BOOK_ON_BOOKSHELF_SUCCESS =
  'DELETE_BOOK_ON_BOOKSHELF_SUCCESS';
export const DELETE_BOOK_FROM_BOOKLIST_SUCCESS =
  'DELETE_BOOK_FROM_BOOKLIST_SUCCESS';
export const FETCH_BOOKSHELF_GENRES_SUCCESS = 'FETCH_BOOKSHELF_GENRES_SUCCESS';
export const FETCH_BOOKSHELF_GENRES_FAILURE = 'FETCH_BOOKSHELF_GENRES_FAILURE';
export const SELECTED_GENRES = 'SELECTED_GENRES';
