export const FETCH_BOOKSHELF_HAS_ERRORED = 'FETCH_BOOKSHELF_HAS_ERRORED';
export const FETCH_BOOKSHELF_IS_LOADING = 'FETCH_BOOKSHELF_IS_LOADING';
export const FETCH_BOOKSHELF_SUCCESS = 'FETCH_BOOKSHELF_SUCCESS';
export const SAVE_COMBINED_BOOKS_SUCESS = 'SAVE_COMBINED_BOOKS_SUCESS';
export const ADD_BOOK_TO_BOOKSHELF_SUCCESS = 'ADD_BOOK_TO_BOOKSHELF_SUCCESS';
